ShopKeeper/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopKeeper.Data;
using ShopKeeper.Migrations;
using ShopKeeper.Models;

namespace ShopKeeper.Controllers
{
    public class DemoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DemoController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult DemoForm()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> DemoForm([Bind("FirstName,LastName")] DemoModel demo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(demo);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(DemoForm));
            }
            return View(demo);
        }

    }
}

ShopKeeper/Views/Demo/DemoForm.cshtml
@model ShopKeeper.Models.DemoModel;

@{
    ViewData["Title"] = "DemoForm";
}
<br>
<h2>DemoForm</h2>
<form asp-action="DemoForm" asp-controller="Demo">
    <label asp-for="FirstName"></label><br>
    <input asp-for="FirstName" placeholder="FirstName.." /><br><br>
    <label asp-for="LastName"></label><br>
    <input asp-for="LastName" placeholder="LastName.." /></br>
    <input type="submit" />
    </form>